version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8038:80

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=test"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test"
      - "MYSQL_ROOT_PASSWORD=test"
    ports:
      - "33070:3306"

volumes:
  dbdata:
